# Generated by Django 5.1.1 on 2024-09-23 23:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_page_options_page_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
