# Generated by Django 5.1.1 on 2024-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-created"],
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(upload_to="services"),
        ),
    ]
