# Generated by Django 5.1.1 on 2024-09-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(related_name="get_posts", to="blog.category"),
        ),
    ]
